// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $("#add_new_post").hide();
    $("#button_new_post_div").hide();
    $("#comments_title").hide();
    $("#buttonBackToHotelList").hide();
    $("#button_new_post").click(function() {
      return $("#add_new_post").show();
    });
    $("#buttonBackToHotelList").click(function() {
      $("#comments").hide();
      $("#hotels").show();
      $("#add_new_post_div").hide();
      $("#button_new_post_div").hide();
      $("#comments_title").hide();
      return $("#hotels_title").show();
    });
    $("#button_create_post").click(function() {
      var content, hotel_id, username;
      username = $("#form-username").first()[0].value;
      content = $("#form-content").first()[0].value;
      hotel_id = window.hotel_focus;
      return $.ajax('/index.php/services/createComment', {
        type: 'POST',
        dataType: 'json',
        data: {
          'author': username,
          'content': content,
          'hotel_id': hotel_id
        },
        error: function(jqXHR, textStatus, errorThrown) {
          return alert(textStatus);
        },
        success: function(data, textStatus, jqXHR) {
          alert("Votre commentaire a bien été enregistré !");
          return $("#add_new_post").hide();
        }
      });
    });
    return $("#comment-edit-send").click(function() {
      var new_value;
      new_value = {
        content: $("#comment-edit-form input").first().val()
      };
      return $.post($("#comment-edit-form").attr('action'), new_value, function(res) {
        var comment, hotel, id, myHotel, _i, _j, _len, _len1, _ref, _ref1;
        myHotel = null;
        id = $("#comment-edit-form").data('commentid');
        _ref = window.list_instance.hotels;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          hotel = _ref[_i];
          if (hotel.id === hotel_focus) {
            _ref1 = hotel.commentList.comments;
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              comment = _ref1[_j];
              if (comment.id === id) {
                comment.content = new_value.content;
                break;
              }
            }
          }
        }
        $(".content-" + id).html(new_value.content);
        return $("#infos").modal('hide');
      }, "json");
    });
  });

  window.HotelList = (function() {
    function HotelList() {
      var _this = this;
      this.hotels = [];
      this.getHotels();
      setInterval(function() {
        return _this.updateHotelListFromId();
      }, 5000);
    }

    HotelList.prototype.getHotels = function() {
      var klass;
      klass = this;
      return $.getJSON("/index.php/services/getHotels", function(res) {
        return $.each(res, function(elem) {
          var hotel;
          hotel = new Hotel(this);
          klass.hotels.push(hotel);
          hotel.show();
          return hotel.bind();
        });
      });
    };

    HotelList.prototype.updateHotelListFromId = function() {
      var id, klass;
      klass = this;
      if (this.hotels.length > 0) {
        id = this.hotels[0].id;
        $.ajaxSetup({
          async: false
        });
        return $.getJSON("/index.php/services/getHotelsFromId/" + id, function(res) {
          var newHotels;
          newHotels = [];
          $.each(res, function(elem) {
            var hotel;
            hotel = new Hotel(this);
            newHotels.push(hotel);
            hotel.top();
            hotel.bind();
            return "";
          });
          return klass.hotels = newHotels.concat(klass.hotels);
        });
      }
    };

    return HotelList;

  })();

  window.CommentList = (function() {
    function CommentList(hotel_id) {
      var _this = this;
      this.hotel_id = hotel_id;
      this.comments = [];
      setInterval(function() {
        return _this.updateCommentListForHotel();
      }, 5000);
    }

    CommentList.prototype.getCommentsForHotel = function() {
      var klass;
      klass = this;
      $.ajaxSetup({
        async: false
      });
      return $.getJSON("/index.php/services/getCommentsForHotel/" + this.hotel_id, function(res) {
        $.each(res, function(elem) {
          var comment;
          comment = new Comment(this);
          klass.comments.push(comment);
          return comment.bind();
        });
        return "";
      });
    };

    CommentList.prototype.updateCommentListForHotel = function() {
      var id, klass;
      klass = this;
      if (this.comments.length > 0) {
        id = this.comments[0].id;
        $.ajaxSetup({
          async: false
        });
        return $.getJSON("/index.php/services/getCommentsFromId/" + hotel_focus + "/" + id, function(res) {
          var newComments;
          newComments = [];
          $.each(res, function(elem) {
            var comment;
            comment = new Comment(this);
            newComments.push(comment);
            comment.top();
            comment.bind();
            return "";
          });
          return klass.comments = newComments.concat(klass.comments);
        });
      }
    };

    CommentList.prototype.show = function() {
      var comment, klass, _i, _len, _ref, _results;
      klass = this;
      $("#hotels").hide();
      $("#comments").show();
      $("#comments_title").show();
      $("#hotels_title").hide();
      $("#button_new_post_div").show();
      $("#ul_comments").html("");
      _ref = this.comments;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        comment = _ref[_i];
        _results.push(window.renderer_instance.showComment(comment));
      }
      return _results;
    };

    return CommentList;

  })();

  window.Hotel = (function() {
    function Hotel(json) {
      this.json = json;
      this.id = json.id;
      this.name = json.name;
      this.cityname = json.cityname;
      this.address = json.address;
      this.commentList = new window.CommentList(this.id);
    }

    Hotel.prototype.show = function() {
      return window.renderer_instance.showHotel(this);
    };

    Hotel.prototype.top = function() {
      return window.renderer_instance.topHotel(this);
    };

    Hotel.prototype.bind = function() {
      var elem, klass;
      klass = this;
      return elem = $("*[data-hotelid='" + this.id + "']").find(".showCommentsForHotel").first().click(function() {
        var html;
        $("#buttonBackToHotelList").show();
        html = klass.name + ", " + klass.cityname;
        $("#hotel_title_name").html(html);
        window.hotel_focus = klass.id;
        klass.commentList.getCommentsForHotel(klass.id);
        return klass.commentList.show();
      });
    };

    return Hotel;

  })();

  window.Comment = (function() {
    function Comment(json) {
      var customDate, day, month;
      this.json = json;
      this.id = json.id;
      this.author = json.author;
      this.creation_date = json.creation_date;
      this.content = json.content;
      customDate = new Date(json.creation_date.date);
      day = customDate.getDay() < 10 ? "0" + customDate.getDay() : customDate.getDay();
      month = customDate.getMonth() < 10 ? "0" + customDate.getMonth() : customDate.getMonth();
      this.final_date = day + "/" + month + "/" + customDate.getFullYear();
    }

    Comment.prototype.show = function() {
      return window.renderer_instance.showComment(this);
    };

    Comment.prototype.top = function() {
      return window.renderer_instance.topComment(this);
    };

    Comment.prototype.bind = function() {
      var klass;
      klass = this;
      $("*[data-commentid='" + this.id + "']").first().hover(function() {
        var fadeDiv;
        fadeDiv = $(this).find("#modify_comment");
        if (!fadeDiv.hasClass('pinned')) {
          return fadeDiv.show();
        }
      }, function() {
        var fadeDiv;
        fadeDiv = $(this).find("#modify_comment");
        if (!fadeDiv.hasClass('pinned')) {
          return fadeDiv.hide();
        }
      });
      $("#edit-from-comment-list-" + klass.id).live('click', function() {
        var id;
        id = $(this).data("commentid");
        $('.comment-edit-value').val("" + klass.content);
        $("#comment-edit-form").attr('action', "/index.php/services/updateComment/" + id);
        return $("#comment-edit-form").attr('data-commentid', id);
      });
      return "";
    };

    return Comment;

  })();

  window.Renderer = (function() {
    function Renderer() {}

    Renderer.prototype.showHotel = function(hotel) {
      var html;
      html = "<li data-hotelid='" + hotel.id + "'><div id='hotel_content'>";
      html += "<span id='hotel_name'>" + hotel.name + ", </span>";
      html += "<span id='hotel_cityname'>" + hotel.cityname + "</span><br/>";
      html += "<span id='hotel_address'>" + hotel.address + "</span><br/>";
      html += "<a href='#' class='showCommentsForHotel'>Afficher les commentaires sur cet hôtel</a>";
      html += "</div></li>";
      return $("#ul_hotels").append(html);
    };

    Renderer.prototype.topHotel = function(hotel) {
      var html;
      html = "<li data-hotelid='" + hotel.id + "'><div id='hotel_content'>";
      html += "<span id='hotel_name'>" + hotel.name + ", </span>";
      html += "<span id='hotel_cityname'>" + hotel.cityname + "</span><br/>";
      html += "<span id='hotel_address'>" + hotel.address + "</span><br/>";
      html += "<a href='#' class='showCommentsForHotel'>Afficher les commentaires sur cet hôtel</a>";
      html += "</div></li>";
      return $("#ul_hotels").prepend(html);
    };

    Renderer.prototype.showComment = function(comment) {
      var html;
      html = "<li data-commentid='" + comment.id + "'><div id='comment_content'>";
      html += "<span id='comment_author'>De : " + comment.author + "</span>";
      html += "<span id='comment_creation_date'> - Commentaire écrit le " + comment.final_date + "</span><br/>";
      html += ("<span id='comment_text' class='content-" + comment.id + "'>") + comment.content + "</span><br/>";
      html += ("<a class='btn edit-from-comment-list' data-toggle='modal' href='#infos' id='edit-from-comment-list-" + comment.id + "' data-commentid=") + comment.id + "><img src='/resources/images/edit.png'></a>";
      html += "</div></li>";
      return $("#ul_comments").append(html);
    };

    Renderer.prototype.topComment = function(comment) {
      var html;
      html = "<li data-commentid='" + comment.id + "'><div id='comment_content'>";
      html += "<span id='comment_author'>De : " + comment.author + "</span>";
      html += "<span id='comment_creation_date'> - Commentaire écrit le " + comment.final_date + "</span><br/>";
      html += ("<span id='comment_text' class='content-" + comment.id + "'>") + comment.content + "</span><br/>";
      html += "<a class='btn' data-toggle='modal' href='#infos' data-commentid=" + comment.id + (" id='edit-from-comment-list-" + comment.id + "'><img src='/resources/images/edit.png'></a>");
      html += "</div></li>";
      return $("#ul_comments").prepend(html);
    };

    return Renderer;

  })();

}).call(this);
